files:
  - source: packages/shared/src/locales/en.json
    dest: /packages/shared/src/locales/en.json
    translation: /packages/shared/src/locales/%two_letters_code%.json
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
