// Transak and Coingecko supported fiat currencies intersection
export enum FiatCurrency {
    USD = 'usd',
    EUR = 'eur',
    GBP = 'gbp',
    AED = 'aed',
    ARS = 'ars',
    AUD = 'aud',
    BHD = 'bhd',
    BMD = 'bmd',
    BRL = 'brl',
    CAD = 'cad',
    CHF = 'chf',
    CLP = 'clp',
    CZK = 'czk',
    DKK = 'dkk',
    GEL = 'gel',
    HKD = 'hkd',
    HUF = 'huf',
    IDR = 'idr',
    ILS = 'ils',
    INR = 'inr',
    JPY = 'jpy',
    KRW = 'krw',
    KWD = 'kwd',
    MXN = 'mxn',
    MYR = 'myr',
    NOK = 'nok',
    NZD = 'nzd',
    PHP = 'php',
    PLN = 'pln',
    SEK = 'sek',
    SGD = 'sgd',
    TWD = 'twd',
}
