import $ from '../../../../shared/src/locales/en.json'

export const MENU_STATE = {
    enabled: true,
    strings: {
        about: $.views.settings.about.title,
        addAccount: $.actions.addAccount,
        advanced: $.views.settings.advanced.title,
        checkForUpdates: $.actions.checkForUpdates,
        copy: $.actions.copy,
        cut: $.actions.cut,
        developerTools: $.general.developerTools,
        diagnostics: $.views.settings.diagnostics.title,
        discord: $.views.settings.discord.title,
        documentation: $.views.settings.documentation.title,
        edit: $.actions.edit,
        errorLog: $.views.settings.errorLog.title,
        faq: $.views.settings.faq.title,
        help: $.general.help,
        hide: $.actions.hide,
        hideOthers: $.actions.hideOthers,
        importThirdPartyProfiles: $.actions.importThirdPartyProfiles,
        logout: $.views.dashboard.profileMenu.logout,
        paste: $.actions.paste,
        quit: $.actions.quit,
        redo: $.actions.redo,
        reportAnIssue: $.actions.reportAnIssue,
        security: $.views.settings.security.title,
        selectAll: $.actions.selectAll,
        settings: $.views.settings.settings,
        showAll: $.actions.showAll,
        undo: $.actions.undo,
        version: $.general.versionFull,
        wallet: $.general.wallet,
    },
}
