export * from './buildSupportedNamespaceFromSelections'
export * from './clearOldPairings'
export * from './disconnectDapp'
export * from './initializeWalletConnect'
export * from './pairWithNewDapp'
export * from './removeDapp'
