name: Test

on:
    pull_request:
        types: [ready_for_review]
    pull_request_review:
        types: [submitted]

jobs:
    shared:
        name: Shared
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.10.0

            - name: Set up .npmrc file to use GitHub Packages
              run: |
                  echo "@bloomwalletio:registry=https://npm.pkg.github.com/" >> .npmrc
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_PERSONAL_ACCESS_TOKEN }}" >> .npmrc

            - name: Install Dependencies
              run: yarn --ignore-scripts

            - name: Test
              run: yarn test:shared
