name: Publish Docs

on:
  push:
    branches:
      - 'develop'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: retypeapp/action-build@v3
        with:
          config: docs

      - uses: retypeapp/action-github-pages@v3
        with:
          branch: retype
          update-branch: true
